name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: Build application and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --quiet --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan jwt:secret

      - name: Create database
        run: |
          mkdir -p database
          touch database/testing.sqlite

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run unit and feature tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/testing.sqlite
        run: |
          php artisan config:clear --ansi
          php artisan test

      - name: Run code quality checks
        run: |
          vendor/bin/pint --test
          vendor/bin/phpstan analyse
          vendor/bin/rector process --dry-run
